// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }
// // import type { Metadata } from "next";
// // import { Raleway, Mulish } from 'next/font/google';
// // import "./globals.css";
// // import { cn } from "~/lib/utils"; // Import utilitas ShadCN

// // // Konfigurasi font (berdasarkan src/index.css)
// // const raleway = Raleway({
// //   subsets: ['latin'],
// //   variable: '--font-raleway', // Buat variabel CSS
// //   display: 'swap',
// // });

// // const mulish = Mulish({
// //   subsets: ['latin'],
// //   variable: '--font-mulish', // Buat variabel CSS
// //   display: 'swap',
// //   weight: ['700', '800', '900'] // Tentukan bobot yang digunakan untuk heading
// // });

// // // Metadata situs (menggantikan <title> di index.html)
// // export const metadata: Metadata = {
// //   title: "Portfolio",
// //   description: "Crafting Interfaces, One Line at a Time",
// // };

// // export default function RootLayout({
// //   children,
// // }: {
// //   children: React.ReactNode;
// // }) {
// //   return (
// //     <html lang="en">
// //       <body 
// //         className={cn(
// //           "min-h-screen bg-white font-body", // Kelas dari App.jsx
// //           raleway.variable, // Terapkan variabel font body
// //           mulish.variable, // Terapkan variabel font heading
// //           "font-sans" // Fallback
// //         )}
// //       >
// //         {/* Terapkan font menggunakan kelas CSS */}
// //         <style jsx global>{`
// //           body {
// //             font-family: var(--font-raleway), sans-serif;
// //           }
// //           h1, h2, h3, h4, h5, h6 {
// //             font-family: var(--font-mulish), sans-serif;
// //           }
// //         `}</style>
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }

// import type { Metadata } from "next";
// import { Raleway, Mulish } from 'next/font/google';
// import "./globals.css";
// import { cn } from "@/lib/utils"; // Error ini akan kita perbaiki di langkah 2

// // Konfigurasi font (berdasarkan src/index.css)
// const raleway = Raleway({
//   subsets: ['latin'],
//   variable: '--font-raleway', 
//   display: 'swap',
// });

// const mulish = Mulish({
//   subsets: ['latin'],
//   variable: '--font-mulish', 
//   display: 'swap',
//   weight: ['700', '800', '900'] 
// });

// // Metadata situs (menggantikan <title>)
// export const metadata: Metadata = {
//   title: "PlatUI Portfolio",
//   description: "Crafting Interfaces, One Line at a Time",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body 
//         className={cn(
//           "min-h-screen bg-white font-body", //
//           raleway.variable, 
//           mulish.variable, 
//           "font-sans" 
//         )}
//       >
//         {/* Terapkan font menggunakan kelas CSS */}
//         <style jsx global>{`
//           body {
//             font-family: var(--font-raleway), sans-serif;
//           }
//           h1, h2, h3, h4, h5, h6 {
//             font-family: var(--font-mulish), sans-serif;
//           }
//         `}</style>
//         {children}
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Raleway, Mulish } from 'next/font/google';
import "./globals.css";
import { cn } from "@/lib/utils"; // Menggunakan alias @/

// Konfigurasi font
const raleway = Raleway({
  subsets: ['latin'],
  variable: '--font-raleway', 
  display: 'swap',
});

const mulish = Mulish({
  subsets: ['latin'],
  variable: '--font-mulish', 
  display: 'swap',
  weight: ['700', '800', '900'] 
});

// Metadata situs
export const metadata: Metadata = {
  title: "PlatUI Portfolio",
  description: "Crafting Interfaces, One Line at a Time",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* HAPUS <style jsx global> dari sini.
        Kita hanya akan meneruskan variabel CSS. 
        'font-sans' akan menjadi font default (Raleway)
      */}
      <body 
        className={cn(
          "min-h-screen bg-white font-sans", // 'font-sans' akan kita definisikan di tailwind.config.ts
          raleway.variable, 
          mulish.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}